<?php

namespace AppBundle\Repository;

/**
 * pages_frontRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pages_frontRepository extends \Doctrine\ORM\EntityRepository
{
}
