<?php

namespace AppBundle\Repository;

/**
 * to_do_listRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class to_do_listRepository extends \Doctrine\ORM\EntityRepository
{
}
